version: 2.1

orbs:
  ms-teams-notifier: wasikuss/ms-teams-notifier@dev:1b6e31f381d6a67c24f2b799bb2691c84fb61ce1

jobs:
  build:
    docker:
      image: cimg/base:current
    steps:
      - run:
          name: Do something
          command: |
            echo 1
      - ms-teams-notifier/report:
          only_on_fail: true
          webhook_url: $WEBHOOK_URL

workflows:
  build:
    jobs:
      - build

