version: 2.1

orbs:
  ms-teams-notifier: wasikuss/ms-teams-notifier@dev:875b973125c2abbb3fd880db6f45fa277066afdd

jobs:
  build:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: Do something
          command: |
            echo 1
      - run:
          name: fail
          command: |
            exit 1
      - run:
          when: on_fail
          name: fail
          command: |
            echo $WEBHOOK_URL
      - ms-teams-notifier/report:
          only_on_fail: true
          show_msg: true
          show_author: true
          webhook_url: $WEBHOOK_URL

workflows:
  do-build:
    jobs:
      - build

